args0 <- commandArgs(trailingOnly = FALSE)
filearg <- sub("^--file=", "", grep("^--file=", args0, value = TRUE)[1])
root <- dirname(normalizePath(filearg))
Sys.setenv(SMART_PROGRAM_DIR = root); setwd(root)
source(file.path(root, "R", "load_all.R"))
s <- summarize_all(); plot_scaled_gaps(s)
write_population_orthogonality_checks()
summarize_secondary_all(); summarize_decomposition_all()
print(s$gap)
