#!/usr/bin/env Rscript
ca <- commandArgs(trailingOnly = FALSE)
hit <- grep("^--file=", ca, value = TRUE)
root <- if (length(hit)) dirname(normalizePath(sub("^--file=", "", hit[1]), mustWork = FALSE)) else normalizePath(getwd())
source(file.path(root, "R", "additional_sim_functions.R"))
old_warn <- getOption("warn")
options(warn = 2)
on.exit(options(warn = old_warn), add = TRUE)
run_smoke_checks()
ctl <- add_control("debug")
# One complete replicate of each new simulation family.
z1 <- simulate_transport_replicate(250, 3, 1, 3, seed = 11, a_values = c(1,2))
stopifnot(all(is.finite(z1$risk_stage1)), all(is.finite(z1$risk_stage2)))
z2 <- simulate_feedback_replicate(250, 1, 3, seed = 12, a = 1)
stopifnot(all(is.finite(z2$risk_stage1)))
z3 <- simulate_finite_library_replicate(250, c(1,1,1), seed = 13)
stopifnot(all(is.finite(z3$risk_SEL)), all(is.finite(z3$risk_MA)))
cat("All additional-simulation smoke checks passed.\n")
print(z1)
print(z2)
print(z3)
